ALTER TABLE pb_state ADD COLUMN region TEXT NOT NULL DEFAULT 'ranch';
ALTER TABLE pb_state ADD COLUMN pos_x INTEGER NOT NULL DEFAULT 7;
ALTER TABLE pb_state ADD COLUMN pos_y INTEGER NOT NULL DEFAULT 5;
ALTER TABLE pb_state ADD COLUMN last_interact_at TEXT;
