// Loads the Pokedex data generated by server/scripts/build-pokedex.mjs.
// That file lives in the git-ignored, volume-mounted data/ dir and may not
// exist yet on a fresh deploy, so loading is lazy and retries on every call
// until it succeeds rather than caching a permanent failure.
import fs from "node:fs";
import path from "node:path";
import { dataDir } from "../db.js";
import { biomeForTypes } from "./pbConstants.js";

export const pbDataDir = path.join(dataDir, "pokemon-breeder");
export const pbSpritesDir = path.join(pbDataDir, "sprites");
const dexPath = path.join(pbDataDir, "pokedex.json");

let cachedDex = null;
let speciesKeysByBiome = null;

export function loadDex() {
  if (cachedDex) return cachedDex;
  try {
    cachedDex = JSON.parse(fs.readFileSync(dexPath, "utf8"));
  } catch {
    return null;
  }
  return cachedDex;
}

export function isDexReady() {
  return loadDex() != null;
}

export function getEntry(speciesKey) {
  const dex = loadDex();
  return dex ? dex.entries[speciesKey] || null : null;
}

export function biomeForEntry(entry) {
  return biomeForTypes(entry.types);
}

function keysByBiome() {
  if (speciesKeysByBiome) return speciesKeysByBiome;
  const dex = loadDex();
  if (!dex) return {};
  speciesKeysByBiome = {};
  for (const [key, entry] of Object.entries(dex.entries)) {
    const biome = biomeForEntry(entry);
    (speciesKeysByBiome[biome] ||= []).push(key);
  }
  return speciesKeysByBiome;
}

export function randomSpeciesKeyForBiome(biome) {
  const keys = keysByBiome()[biome];
  if (!keys || keys.length === 0) return null;
  return keys[Math.floor(Math.random() * keys.length)];
}

export function randomSpeciesKey() {
  const dex = loadDex();
  if (!dex) return null;
  const keys = Object.keys(dex.entries);
  return keys[Math.floor(Math.random() * keys.length)];
}
