services:
  arcadia:
    environment:
      ADMIN_PASSWORD: change-me-before-deploying
      ADMIN_USERNAME: admin
      TRUST_PROXY: 'true'
    image: ghcr.io/ramblepaw/arcadia:latest
    ports:
      - '8090:8090'
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /mnt/Main Store/Apps/Arcadia/data:/data
